version: '3.8'

services:
  # Traefik - Load Balancer & Reverse Proxy for Multi-tenant Architecture
  traefik:
    image: traefik:v2.10
    container_name: zplus-traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS  
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - zplus-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"

  # Database Services
  postgres:
    image: postgres:15-alpine
    container_name: zplus-postgres
    environment:
      POSTGRES_DB: zplus_saas
      POSTGRES_USER: zplus_user
      POSTGRES_PASSWORD: zplus_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - zplus-network
    restart: unless-stopped

  mongodb:
    image: mongo:7-jammy
    container_name: zplus-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: zplus_user
      MONGO_INITDB_ROOT_PASSWORD: zplus_password
      MONGO_INITDB_DATABASE: zplus_saas
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - zplus-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: zplus-redis
    command: redis-server --appendonly yes --requirepass zplus_password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - zplus-network
    restart: unless-stopped

  # Development services (optional)
  adminer:
    image: adminer
    container_name: zplus-adminer
    ports:
      - "8090:8080"  # Changed to avoid conflict with Traefik dashboard
    networks:
      - zplus-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  zplus-network:
    driver: bridge