apiVersion: v1
kind: Namespace
metadata:
  name: zplus-saas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: zplus-saas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway
        image: zplus-saas/gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: postgres-service
        - name: REDIS_HOST
          value: redis-service
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: zplus-saas
spec:
  selector:
    app: gateway-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP